
import java.awt.Image;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileOutputStream;
import java.nio.channels.FileChannel;
import javax.swing.JFrame;
import java.util.Calendar;
import java.util.Random;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class add_emp extends javax.swing.JFrame {

    /**
     * Creates new form add_emp
     */
    public static final int CREATE=0;
    public static int todo=0;
    public static String empi;
    public static final int UPDATE=1;
    public add_emp() {
        initComponents();
        todo=0;
        setExtendedState(JFrame.MAXIMIZED_VERT);
        dat.setVisible(false);
        
    }
    public add_emp(ResultSet rs) {
        initComponents();
        todo=1;
        jButton2.setText("UPDATE");
        jButton1.setVisible(false);
        year.setVisible(false);
        month.setVisible(false);
        jButton4.setVisible(false);
        date.setVisible(false);
        y1.setVisible(false);
        m1.setVisible(false);
        d1.setVisible(false);
        dat.setVisible(true);
        jLabel4.setText("JOINING DATE");
        setExtendedState(JFrame.MAXIMIZED_VERT);
        try
        {
            System.out.println(todo);
            rs.next();
            empi=rs.getString(1);
             ename.setText(rs.getString(2));
        ephone.setText(rs.getString(3));
        uidno.setText(rs.getString(12));
        empImg.setIcon(null);
        address.setText(rs.getString(4));
        eemail.setText(rs.getString(6));
        year.setSelectedIndex(0);
        sal.setText(rs.getString(8));
        dat.setText(rs.getString(7));
        target.setText(rs.getString(9));
        location.setSelectedIndex(1);
        zip.setText(rs.getString(5));
        location.setSelectedIndex(rs.getInt(11)-1);
        dpt.setSelectedIndex(rs.getInt(10)-1);
        
         String picfile = "H:\\Employess_Pic\\"+rs.getString(1)+".jpg";
         
         System.out.println("Zip::"+rs.getString(5)+"pic img "+picfile);
         ImageIcon imgic = new ImageIcon(picfile); 
           Image imFit = imgic.getImage();
           Image imgFit = imFit.getScaledInstance(empImg.getWidth() , empImg.getHeight(), Image.SCALE_SMOOTH);
           empImg.setIcon(new ImageIcon(imgFit));
         
        }catch(Exception e)
        {
            System.out.println(e);
        }
        
    }
    public static String filepath;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCalendar2 = new com.toedter.calendar.JCalendar();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        ename = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        ephone = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        eemail = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        y1 = new javax.swing.JLabel();
        year = new javax.swing.JComboBox<>();
        m1 = new javax.swing.JLabel();
        month = new javax.swing.JComboBox<>();
        d1 = new javax.swing.JLabel();
        date = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        sal = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        target = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        address = new javax.swing.JTextArea();
        jLabel13 = new javax.swing.JLabel();
        zip = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        dpt = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        location = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        uidno = new javax.swing.JTextField();
        empImg = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        dat = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(190, 171, 243));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel1.setText("NAME");

        ename.setBackground(new java.awt.Color(204, 204, 255));
        ename.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("PHONE NUMBER");

        ephone.setBackground(new java.awt.Color(204, 204, 255));
        ephone.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("E-mail");

        eemail.setBackground(new java.awt.Color(204, 204, 255));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("JOINING DATE (it will not change)");

        y1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        y1.setText("Year:");

        year.setBackground(new java.awt.Color(204, 204, 255));
        year.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "---Year---", "1960", "1961", "1962", "1963", "1964", "1965", "1966", "1967", "1968", "1969", "1970", "1971", "1972", "1973", "1974", "1975", "1976", "1977", "1978", "1979", "1980", "1981", "1982", "1983", "1984", "1985", "1986", "1987", "1988", "1989", "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005", "2006", "2007", "2008", "2009", "2010", "2011", "2012", "2013", "2014", "2015", "2016", "2017", "2018", "2019", "2020", "2021" }));
        year.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                yearActionPerformed(evt);
            }
        });

        m1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        m1.setText("Month:");

        month.setBackground(new java.awt.Color(204, 204, 255));
        month.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12" }));
        month.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthActionPerformed(evt);
            }
        });

        d1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        d1.setText("Date:");

        date.setBackground(new java.awt.Color(204, 204, 255));

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel5.setText("BASICS SALARY");

        sal.setBackground(new java.awt.Color(204, 204, 255));
        sal.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel6.setText("TARGET");

        target.setBackground(new java.awt.Color(204, 204, 255));
        target.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel12.setText("ADDRESS");

        address.setBackground(new java.awt.Color(204, 204, 255));
        address.setColumns(20);
        address.setRows(5);
        address.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jScrollPane1.setViewportView(address);

        jLabel13.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel13.setText("ZIP CODE");

        zip.setBackground(new java.awt.Color(204, 204, 255));
        zip.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel7.setText("DEPARTMENT");

        dpt.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        dpt.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SALES", "ADMINSTRATOR", "MANAGER", "STAFF", "WAITER", "SECURITY", "CHEFF", "ASSISTENT" }));

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel8.setText("LOCATION");

        location.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        location.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DELHI", "MUMBAI", "KOLKATA", "HOWRA", "JAMSHEDPUR", "MANGO", "SIDGORA", " BARIDIH" }));

        jButton1.setBackground(new java.awt.Color(255, 255, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setText("RESET");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(102, 255, 102));
        jButton2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton2.setText("SUBMIT");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton3.setText("CANCEL");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel14.setText("AADHAR CARD NUMBER");

        uidno.setBackground(new java.awt.Color(204, 204, 255));
        uidno.setFont(new java.awt.Font("Trebuchet MS", 0, 14)); // NOI18N

        empImg.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jButton4.setBackground(new java.awt.Color(51, 255, 204));
        jButton4.setText("CHOOSE IMAGE");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        dat.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        dat.setText("jLabel9");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(ename, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(uidno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(47, 47, 47)
                                            .addComponent(jLabel1))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(43, 43, 43)
                                            .addComponent(jLabel2))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(46, 46, 46)
                                            .addComponent(jLabel3))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel5))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(31, 31, 31)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                .addComponent(jLabel12)
                                                .addComponent(jLabel6))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(35, 35, 35)
                                            .addComponent(jLabel13)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(24, 24, 24)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabel7)
                                                .addComponent(jLabel8)
                                                .addComponent(jLabel14))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(dpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(jPanel1Layout.createSequentialGroup()
                                            .addGap(21, 21, 21)
                                            .addComponent(y1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(dat)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(m1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(d1)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGap(6, 6, 6))))
                        .addGap(38, 38, 38))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(eemail, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(sal, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 340, Short.MAX_VALUE))
                            .addComponent(jLabel4)
                            .addComponent(ephone, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addComponent(empImg, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(41, 41, 41))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(58, 58, 58))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(ename, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ephone, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(eemail, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(y1)
                            .addComponent(year, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(m1)
                            .addComponent(month, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(d1)
                            .addComponent(date, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(sal, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addComponent(empImg, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(target, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(zip, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(dpt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(location, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14)
                .addGap(18, 18, 18)
                .addComponent(uidno, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        dbcon c = new dbcon();
                      Connection con = c.connection();
                        
        if(todo==CREATE)
        {
                    int max = 999999;
                    int min = 100000;
                    int id = (int)(Math.random()*(max-min+1)+min);
                    String empid = "E"+id;
                    System.out.println(empid);
                    // YYYY-MM-DD
                    String dat = year.getSelectedItem()+"-"+month.getSelectedItem()+"-"+date.getSelectedItem();
                    System.out.println(dat);
                    String picfile = "H:\\Employess_Pic\\"+empid+".jpg";

                    File infile = new File(filepath);
                    File outfile = new File(picfile);
                    
                    String str = "insert into coffeeshop.employee values('"+empid+"','"+ename.getText()+"','"+ephone.getText()+"','"+address.getText()+"',"+zip.getText()+",'"+eemail.getText()+"','"+dat+"',"+sal.getText()+","+target.getText()+",'"+dpt.getSelectedIndex()+"','"+location.getSelectedIndex()+"','"+uidno.getText()+"','"+picfile+"','');";//uidno
                    System.out.println(str);
                    try{
                        Statement stm = con.createStatement();
                        stm.execute(str);
                        JOptionPane.showMessageDialog(this, "Employee Added successfully!!!!");
                        ename.setText("");
                    ephone.setText("");
                    uidno.setText("");
                    empImg.setIcon(null);
                    address.setText("");
                    eemail.setText("");
                    year.setSelectedIndex(0);
                    sal.setText("");
                    target.setText("");
                    location.setSelectedIndex(0);
                    zip.setText("");
                    dpt.setSelectedIndex(0);
                     try {
                        copyFileUsingNIO(infile,outfile);
                    } catch (Exception e) {
                        e.printStackTrace();
                    }
                    }catch(Exception e)
                    {
                        JOptionPane.showMessageDialog(this, "Error :> "+e);
                    }
        }
        else
        {
            String update = "update coffeeshop.employee set Empname='"+ename.getText()+"' , Empphone ='"+ephone.getText()+"',address='"+address.getText()+"',zipcode='"+zip.getText()+"',Empemail='"+eemail.getText()+"',Basics_sal="+sal.getText()+",target="+target.getText()+",Dept_id='"+(dpt.getSelectedIndex()+1)+"',loc_id='"+(location.getSelectedIndex()+1)+"',aadharno='"+uidno.getText()+"' where Empid='"+empi+"';";
            try
            {
                Statement stm = con.createStatement();
                stm.executeUpdate(update);
                JOptionPane.showMessageDialog(this, "Employee Updated Successully");
                this.dispose();
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error :> "+e);
            }
        }
        
    }//GEN-LAST:event_jButton2MouseClicked

    private void monthActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthActionPerformed
        // TODO add your handling code here:
        date.removeAllItems();
        int m = Integer.parseInt(String.valueOf(month.getSelectedItem()));
        int y = Integer.parseInt(String.valueOf(year.getSelectedItem()));
        if(m==1||m==3||m==10||m==12||m==5||m==7||m==8)
        {
            
             for(int i =1;i<=31;i++)
             {
                 date.addItem(String.valueOf(i));
             }
        }
        else
            if(m==4||m==6||m==9||m==11)
            {
               for(int i =1;i<=30;i++)
             {
                 date.addItem(String.valueOf(i));
             } 
            }
            else if(m==2&&((y%400==0)||(y%4==0&&y%100!=0)))
            {
                for(int i =1;i<=29;i++)
             {
                 date.addItem(String.valueOf(i));
             }   
            }
        else
            {
                  for(int i =1;i<=28;i++)
             {
                 date.addItem(String.valueOf(i));
             } 
            }
    }//GEN-LAST:event_monthActionPerformed

    private void yearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_yearActionPerformed
        // TODO add your handling code here:
        date.removeAllItems();
//        month.addItem("01");
//        month.addItem("02");
//        month.addItem("03");
//        month.addItem("04");
//        month.addItem("05");
//        month.addItem("06");
//        month.addItem("07");
//        month.addItem("08");
//        month.addItem("09");
//        month.addItem("10");
//       month.addItem("11");
//       month.addItem("12");
    }//GEN-LAST:event_yearActionPerformed

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        ename.setText("");
        ephone.setText("");
        address.setText("");
        eemail.setText("");
        year.setSelectedIndex(0);
        sal.setText("");
        target.setText("");
        location.setSelectedIndex(0);
        zip.setText("");
        dpt.setSelectedIndex(0);
    }//GEN-LAST:event_jButton1MouseClicked
    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        JFileChooser filechoose = new JFileChooser();
        FileNameExtensionFilter filter = new FileNameExtensionFilter("3 Extension Supported","jpg","png","jpeg");
        filechoose.setFileFilter(filter);
        int selected = filechoose.showOpenDialog(this);
        if(selected==JFileChooser.APPROVE_OPTION)
        {
            File file = filechoose.getSelectedFile();
            String getSelectedImg = file.getAbsolutePath();
            filepath = getSelectedImg;
           ImageIcon imgic = new ImageIcon(getSelectedImg); 
           Image imFit = imgic.getImage();
           Image imgFit = imFit.getScaledInstance(empImg.getWidth() , empImg.getHeight(), Image.SCALE_SMOOTH);
           empImg.setIcon(new ImageIcon(imgFit));
        }      
        
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(add_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new add_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea address;
    private javax.swing.JLabel d1;
    private javax.swing.JLabel dat;
    private javax.swing.JComboBox<String> date;
    private javax.swing.JComboBox<String> dpt;
    private javax.swing.JTextField eemail;
    private javax.swing.JLabel empImg;
    private javax.swing.JTextField ename;
    private javax.swing.JTextField ephone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private com.toedter.calendar.JCalendar jCalendar2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> location;
    private javax.swing.JLabel m1;
    private javax.swing.JComboBox<String> month;
    private javax.swing.JTextField sal;
    private javax.swing.JTextField target;
    private javax.swing.JTextField uidno;
    private javax.swing.JLabel y1;
    private javax.swing.JComboBox<String> year;
    private javax.swing.JTextField zip;
    // End of variables declaration//GEN-END:variables

    private void copyFileUsingNIO(File infile, File outfile)throws Exception {
       FileInputStream inputStream = new FileInputStream(infile);
        FileOutputStream outputStream = new FileOutputStream(outfile);
        FileChannel inChannel = inputStream.getChannel();
        FileChannel outChannel = outputStream.getChannel();
        try {
            inChannel.transferTo(0, inChannel.size(), outChannel);
        } finally {
            inChannel.close();
            outChannel.close();
            inputStream.close();
            outputStream.close();
        }
    }//To change body of generated methods, choose Tools | Templates.
    }
