/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
import java.awt.Color;
import java.awt.Image;
import java.io.File;
import javax.swing.*;
import java.sql.*;
import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
public class adminMain extends javax.swing.JFrame {

    /**
     * Creates new form adminMain
     */
    public static int SELINDEX;
    public adminMain() {
        
        initComponents();
        selPname.setSelected(true);
        SELINDEX=0;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String q = "SELECT * FROM coffeeshop.employee as a join coffeeshop.dempartement as b on a.dept_id = b.dept_id join coffeeshop.location as c on a.loc_id=c.location_id  ;";
        dbcon con = new dbcon();
        Connection c = con.connection();
        try
        {
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(q);
            while(rs.next())
            {
                       
               model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(15),rs.getString(17)});
            //System.out.println(rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        
        q = "select * from coffeeshop.product";
                try
                {
                    Statement stm = c.createStatement();
                    ResultSet rs = stm.executeQuery(q);
                    while(rs.next())
                    {
                        model1.insertRow(model1.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});
                    }
                }catch(Exception e)
                {
                JOptionPane.showMessageDialog(this, "Product Selection error>> "+e);                    
                }
    }
    public adminMain(String nm) {
        initComponents();
        selPname.setSelected(true);
        name.setText(nm);
        SELINDEX=0;
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        String q = "SELECT * FROM coffeeshop.employee as a join coffeeshop.dempartement as b on a.dept_id = b.dept_id join coffeeshop.location as c on a.loc_id=c.location_id  ;";
        dbcon con = new dbcon();
        Connection c = con.connection();
        try
        {
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(q);
            while(rs.next())
            {
                       
               model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(15),rs.getString(17)});
            //System.out.println(rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
        DefaultTableModel model1 = (DefaultTableModel) jTable3.getModel();
        
        q = "select * from coffeeshop.product";
                try
                {
                    Statement stm = c.createStatement();
                    ResultSet rs = stm.executeQuery(q);
                    while(rs.next())
                    {
                        model1.insertRow(model1.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});
                    }
                }catch(Exception e)
                {
                JOptionPane.showMessageDialog(this, "Product Selection error>> "+e);
                    
                }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        name = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        add_emp = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jButton6 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        selPname = new javax.swing.JRadioButton();
        selPqty = new javax.swing.JRadioButton();
        selPmrp = new javax.swing.JRadioButton();
        jTextField4 = new javax.swing.JTextField();
        prolabel = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        jTable4 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        name.setFont(new java.awt.Font("Trebuchet MS", 0, 24)); // NOI18N
        name.setText("<User name>");

        jButton1.setBackground(new java.awt.Color(255, 51, 51));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("LOGOUT");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Login as:");

        jTable1.setBackground(new java.awt.Color(255, 255, 153));
        jTable1.setFont(new java.awt.Font("Sitka Text", 0, 14)); // NOI18N
        jTable1.setForeground(new java.awt.Color(204, 0, 0));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "EmpID", "EmpName", "EmpPhone", "EmpEmail", "Joining Date", "Basics Sal", "Target", "Dept", "Location"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        add_emp.setBackground(new java.awt.Color(102, 255, 102));
        add_emp.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        add_emp.setText("NEW EMPLOYEE");
        add_emp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_empMouseClicked(evt);
            }
        });
        add_emp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_empActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(255, 102, 102));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("DELETE EMP");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });

        jButton4.setBackground(new java.awt.Color(255, 255, 102));
        jButton4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jButton4.setText("UPDATE EMP");
        jButton4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton4MouseClicked(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(0, 255, 204));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setText("Refresh");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(add_emp, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(jButton2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1403, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 614, Short.MAX_VALUE)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(add_emp)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addComponent(jButton4)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Employee", jPanel1);

        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "product ID", "Name", "Qty", "MRP"
            }
        ));
        jScrollPane3.setViewportView(jTable3);

        jPanel4.setBackground(new java.awt.Color(153, 153, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("ADD NEW PRODUCT"));
        jPanel4.setForeground(new java.awt.Color(153, 153, 255));

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel4.setText("MRP");

        jTextField3.setBackground(new java.awt.Color(204, 204, 255));
        jTextField3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel3.setText("QUANTITY");

        jTextField2.setBackground(new java.awt.Color(204, 204, 255));
        jTextField2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jTextField1.setBackground(new java.awt.Color(204, 204, 255));
        jTextField1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Trebuchet MS", 1, 18)); // NOI18N
        jLabel2.setText("PRODUCT NAME");

        jButton5.setBackground(new java.awt.Color(153, 255, 153));
        jButton5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton5.setText("ADD NEW PRODUCT");
        jButton5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(36, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        jPanel5.setBackground(new java.awt.Color(255, 153, 153));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("DELETE PRODUCT"));

        jButton6.setBackground(new java.awt.Color(255, 255, 51));
        jButton6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton6.setText("DELETE PRODUCT");
        jButton6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton6MouseClicked(evt);
            }
        });
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(182, 182, 182)
                .addComponent(jButton6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton6)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(153, 255, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("UPDATE PRODUCT")));

        jButton7.setBackground(new java.awt.Color(255, 102, 255));
        jButton7.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButton7.setText("UPDATE PRODUCT");
        jButton7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton7MouseClicked(evt);
            }
        });

        selPname.setText("Product Name");
        selPname.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        selPname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPnameActionPerformed(evt);
            }
        });

        selPqty.setText("Product Qty");
        selPqty.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPqtyActionPerformed(evt);
            }
        });

        selPmrp.setText("Product MRP");
        selPmrp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                selPmrpActionPerformed(evt);
            }
        });

        jTextField4.setBackground(new java.awt.Color(204, 255, 204));
        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));

        prolabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        prolabel.setText("NEW NAME");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(120, 120, 120)
                        .addComponent(selPname)
                        .addGap(18, 18, 18)
                        .addComponent(selPqty)
                        .addGap(18, 18, 18)
                        .addComponent(selPmrp))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(prolabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addGap(198, 198, 198)
                        .addComponent(jButton7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(selPname)
                    .addComponent(selPqty)
                    .addComponent(selPmrp))
                .addGap(33, 33, 33)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(prolabel)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(jButton7)
                .addGap(0, 52, Short.MAX_VALUE))
        );

        jButton8.setText("REFRESH");
        jButton8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButton8)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1033, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton8)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 592, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Product", jPanel2);

        jButton9.setText("GENERATE THIS MONTH SALARY");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setText("SHOW ALL PREVIOUS SALARY");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jTable4.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "DATE", "EMPID", "EMPNAME", "EMPEMAIL", "EMP SALARY"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane4.setViewportView(jTable4);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton9)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton10)
                        .addGap(113, 113, 113)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 1163, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(160, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton9)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton10)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Salary Maker", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(127, 127, 127)
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addComponent(name)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(54, 54, 54))
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(name)
                    .addComponent(jButton1)
                    .addComponent(jLabel1))
                .addGap(39, 39, 39)
                .addComponent(jTabbedPane1))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
        admin obj = new admin();
        obj.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jButton1MouseClicked

    private void add_empMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_empMouseClicked
        // TODO add your handling code here:
        add_emp obj = new add_emp();
        obj.setVisible(true);
    }//GEN-LAST:event_add_empMouseClicked

    private void add_empActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_empActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_add_empActionPerformed

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = model.getRowCount();
        int i;
        for(i=row-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        String q = "SELECT * FROM coffeeshop.employee as a join coffeeshop.dempartement as b on a.dept_id = b.dept_id join coffeeshop.location as c on a.loc_id=c.location_id  ;";
        dbcon con = new dbcon();
        Connection c = con.connection();
        try
        {
            Statement stm = c.createStatement();
            ResultSet rs = stm.executeQuery(q);
            while(rs.next())
            {
               model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(15),rs.getString(17)});
            //System.out.println(rs.getString(1));
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
            
    }//GEN-LAST:event_jButton2MouseClicked

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton3MouseClicked

        // TODO add your handling code here:
        try
        {
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        jTable1.setSelectionBackground(Color.ORANGE);
        System.out.println(row);
        String id = String.valueOf(model.getValueAt(row, 0));
        String name= String.valueOf(model.getValueAt(row, 1));
        int cnf =JOptionPane.showConfirmDialog(this,"sure?? Do you want to delete "+name);
        System.out.println(cnf);
        dbcon obj = new dbcon();
        Connection con = obj.connection();
        //yes -> 0 no->1 cancel ->2
        String path = "H:\\Employess_Pic\\"+id+".jpg";
        
        if(cnf==0)
        {
            String delop = "delete from coffeeshop.employee where empid='"+id+"'";
            try
            {
                Statement stm = con.createStatement();
                stm.execute(delop);
                File file = new File(path);
                boolean fi = file.delete();
                if(fi==false)
                {
                 JOptionPane.showMessageDialog(this, "Error >> pic deletion unscuuessfull!!");   
                }
                
                
        int r = model.getRowCount();
        int i;
        for(i=r-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        String q = "select * from coffeeshop.employee;";
        try
        {
            Statement stm1 = con.createStatement();
            ResultSet rs = stm1.executeQuery(q);
            while(rs.next())
            {
               model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getString(3),rs.getString(6),rs.getString(7),rs.getString(8),rs.getString(9),rs.getString(10),});
            //System.out.println(rs.getString(1));
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error >> "+e);
        }
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error >> "+e);
                
            }
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select an Employee row");
        }
    }//GEN-LAST:event_jButton3MouseClicked

    private void jButton4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton4MouseClicked
        // TODO add your handling code here:
        try{
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        int row = jTable1.getSelectedRow();
        System.out.println(row);
        String id = String.valueOf(model.getValueAt(row, 0));
        dbcon obj = new dbcon();
        String st = "select * from coffeeshop.employee where empid='"+id+"'";
        Connection con = obj.connection();
        try
        {
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(st);
            add_emp update = new add_emp(rs);
            update.setVisible(true);
        }catch(Exception e)
        {
            System.out.println("Error >>"+e);
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select an Employee row");
        }
    }//GEN-LAST:event_jButton4MouseClicked

    private void jButton5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton5MouseClicked
        // TODO add your handling code here:
            int max = 999999;
            int min = 100000;
            int id = (int)(Math.random()*(max-min+1)+min);
            String product_id = "P"+id;
            String q = "insert into coffeeshop.product values('"+product_id+"','"+jTextField1.getText()+"',"+jTextField3.getText()+","+jTextField2.getText()+");";
            dbcon obj = new dbcon();
            Connection con = obj.connection();
            try
            {
                Statement stm = con.createStatement();
                stm.execute(q);
                JOptionPane.showMessageDialog(this, "Product Inserted Successfully");
                jTextField1.setText("");
                jTextField2.setText("");
                jTextField3.setText("");
                DefaultTableModel model= (DefaultTableModel) jTable3.getModel();
                int r = model.getRowCount();
                int i;
                for(i=r-1;i>=0;i--)
                {
                    model.removeRow(i);
                }
                q = "select * from coffeeshop.product";
                try
                {
                    ResultSet rs = stm.executeQuery(q);
                    while(rs.next())
                    {
                        model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});
                    }
                }catch(Exception e)
                {
                JOptionPane.showMessageDialog(this, "Product Selection error>> "+e);
                    
                }
            }catch(Exception e)
                {
                    
                JOptionPane.showMessageDialog(this, "Product Insertion Unsuccessful>> "+e);
                }
    }//GEN-LAST:event_jButton5MouseClicked

    private void jButton8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton8MouseClicked
        // TODO add your handling code here:dbcon obj = new dbcon();
        dbcon obj = new dbcon();
            Connection con = obj.connection();
        DefaultTableModel model= (DefaultTableModel) jTable3.getModel();
                int r = model.getRowCount();
                int i;
                for(i=r-1;i>=0;i--)
                {
                    model.removeRow(i);
                }
                
                String q = "select * from coffeeshop.product";
                try
                {
                    Statement stm = con.createStatement();
                    ResultSet rs = stm.executeQuery(q);
                    while(rs.next())
                    {
                        model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});
                    }
                }catch(Exception e)
                {
                JOptionPane.showMessageDialog(this, "Product Selection error>> "+e);
                    
                }
    }//GEN-LAST:event_jButton8MouseClicked

    private void jButton6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton6MouseClicked
        // TODO add your handling code here:jTextField4
        try
        {
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int row = jTable3.getSelectedRow();
        jTable1.setSelectionBackground(Color.ORANGE);
        System.out.println(row);
        String id = String.valueOf(model.getValueAt(row, 0));
        String name= String.valueOf(model.getValueAt(row, 1));
        int cnf =JOptionPane.showConfirmDialog(this,"sure?? Do you want to delete Item>> "+name);
        System.out.println(cnf);
        dbcon obj = new dbcon();
        Connection con = obj.connection();
        //yes -> 0 no->1 cancel ->2
        
        if(cnf==0)
        {
            String delop = "delete from coffeeshop.product where productID='"+id+"'";
            try
            {
                Statement stm = con.createStatement();
                stm.execute(delop);
                
        int r = model.getRowCount();
        int i;
        for(i=r-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        String q = "select * from coffeeshop.product;";
        try
        {
            Statement stm1 = con.createStatement();
            ResultSet rs = stm1.executeQuery(q);
            while(rs.next())
            {
                        model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});                
            }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Error >> "+e);
        }
                
            }catch(Exception e)
            {
                JOptionPane.showMessageDialog(this, "Error >> "+e);
                
            }
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select an Item/Product row");
        }
        
    }//GEN-LAST:event_jButton6MouseClicked

    private void selPqtyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPqtyActionPerformed
        // TODO add your handling code here:
        selPname.setSelected(false);
        selPmrp.setSelected(false);
        selPqty.setSelected(true);
        prolabel.setText("QUANTITY");
        SELINDEX=1;
    }//GEN-LAST:event_selPqtyActionPerformed

    private void selPnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPnameActionPerformed
        // TODO add your handling code here:
        selPname.setSelected(true);
        selPmrp.setSelected(false);
        SELINDEX=0;
        selPqty.setSelected(false);
        prolabel.setText("NEW NAME");
    }//GEN-LAST:event_selPnameActionPerformed

    private void selPmrpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_selPmrpActionPerformed
        // TODO add your handling code here:
        selPname.setSelected(false);
        selPmrp.setSelected(true);
        selPqty.setSelected(false);
        SELINDEX=2;
        prolabel.setText("NEW MRP");
    }//GEN-LAST:event_selPmrpActionPerformed

    private void jButton7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton7MouseClicked
        // TODO add your handling code here:
        try{
        DefaultTableModel model = (DefaultTableModel) jTable3.getModel();
        int row = jTable3.getSelectedRow();
        System.out.println(row);
        String id = String.valueOf(model.getValueAt(row, 0));
        dbcon obj = new dbcon();
        if(SELINDEX==0)
        {
            String q="update coffeeshop.product set product_name ='"+jTextField4.getText()+"' where product.productID='"+id+"'";  
            SelUpdate(q);
        }
        else if(SELINDEX==1)
        {
            String q="update coffeeshop.product set qty =qty+"+Integer.parseInt(jTextField4.getText())+" where product.productID='"+id+"'";   
            SelUpdate(q);
        }
        else if(SELINDEX==2)
        {
            String q="update coffeeshop.product set mrp ="+Integer.parseInt(jTextField4.getText())+" where product.productID='"+id+"'";  
            SelUpdate(q);
        }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Select an Item row");
        }
    }//GEN-LAST:event_jButton7MouseClicked

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int r = model.getRowCount();
        for(int i = r-1;i>=0;i--)
        {
            model.removeRow(i);
        }
            
        String str = "select a.Empid,a.Empname, a.Basics_sal, a.target, a.Empemail, count(a.Empid) from employee a left join sales b on a.Empid = b.empid and year(b.saleDate)=year(sysdate()) and month(b.saleDate)=month(sysdate())  group by(a.Empid)";
        dbcon obj = new dbcon();
        double sal,newsal=0;
        int acta,ccta=0;
        Connection con = obj.connection();
        try
        {
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(str);
            while(rs.next())
            {
               sal = rs.getDouble(3);
                acta = rs.getInt(4);
                try
                {
                    if(rs.getString(1)==null)
                    {
                        ccta=0;
                    }
                    ccta = rs.getInt(6);
                    
                    newsal = new SalaryMaker().salary(acta, ccta, sal);
                    String d = new SimpleDateFormat("yyyy-MM-dd").format(new java.util.Date());
                model.insertRow(model.getRowCount(), new Object[]{d,rs.getString(1),rs.getString(2),rs.getString(5),newsal});
                String s11  = "insert into salary values('"+rs.getString(1)+"',sysdate(),"+newsal+","+ccta+");";
                SendSalary.SendSalary(rs.getString(5), newsal, rs.getString(2),ccta);
                
                stm = con.createStatement();
                stm.execute(s11);
                
                }catch(Exception e)
                                    {
                                        System.out.println(e);
                                    }
                
            }
        }catch(Exception e)
        {
            System.out.println(e);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        // TODO add your handling code here:
        String str = "SELECT * FROM coffeeshop.salary a join employee b on a.empid= b.empid";
         DefaultTableModel model = (DefaultTableModel) jTable4.getModel();
        int r = model.getRowCount();
        for(int i = r-1;i>=0;i--)
        {
            model.removeRow(i);
        }
        dbcon obj = new dbcon();
        Connection con = obj.connection();
         try
        {
            Statement stm = con.createStatement();
            ResultSet rs = stm.executeQuery(str);
            while(rs.next())
            {
                 model.insertRow(model.getRowCount(), new Object[]{rs.getString(2),rs.getString(1),rs.getString(6),rs.getString(10),rs.getString(3)});
            }
        }catch(Exception e)
        {
            
        }
         
            
    }//GEN-LAST:event_jButton10ActionPerformed
public void SelUpdate(String str)
{
        dbcon obj = new dbcon();
        Connection con = obj.connection();
        
        try
        {
            Statement stm = con.createStatement();
            stm.executeUpdate(str);
            JOptionPane.showMessageDialog(this, "Product Update!!");
            DefaultTableModel model= (DefaultTableModel) jTable3.getModel();
            jTextField4.setText("");
                int r = model.getRowCount();
                int i;
                for(i=r-1;i>=0;i--)
                {
                    model.removeRow(i);
                }
                
                String q = "select * from coffeeshop.product";
                try
                {
                    stm = con.createStatement();
                    ResultSet rs = stm.executeQuery(q);
                    while(rs.next())
                    {
                        model.insertRow(model.getRowCount(), new Object[]{rs.getString(1),rs.getString(2),rs.getInt(4),rs.getDouble(3)});
                    }
                }catch(Exception e)
                {
                JOptionPane.showMessageDialog(this, "Product Selection error>> "+e);
                    
                }
        }catch(Exception e)
        {
            JOptionPane.showMessageDialog(this, "Product Updation error>> "+e);
        }
}
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(adminMain.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new adminMain().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton add_emp;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable3;
    private javax.swing.JTable jTable4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JLabel name;
    private javax.swing.JLabel prolabel;
    private javax.swing.JRadioButton selPmrp;
    private javax.swing.JRadioButton selPname;
    private javax.swing.JRadioButton selPqty;
    // End of variables declaration//GEN-END:variables
}
